---
deployment:
  tasks:
    - /usr/local/bin/php $HOME/public_html/inmobiliariabidart_app/artisan migrate --force
    - /usr/local/bin/php $HOME/public_html/inmobiliariabidart_app/artisan optimize:clear
    - mkdir -p $HOME/public_html/inmobiliariabidart/storage/propiedades-alquiler
    - mkdir -p $HOME/public_html/inmobiliariabidart/storage/propiedades-venta
